import pygame

TILE_PIXEL_SIZE = 10
LEVEL_UPDATE = pygame.USEREVENT + 1
PACMAN_UPDATE = pygame.USEREVENT + 2
BLINKY_UPDATE = pygame.USEREVENT + 3
PINKY_UPDATE = pygame.USEREVENT + 4
INKY_UPDATE = pygame.USEREVENT + 5
CLYDE_UPDATE = pygame.USEREVENT + 6
